datadog:
  apm:
    enabled: true
  env: ""
  version: __version__

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

envs:
  ENDPOINT_PREFIX: "/api/items-boxing"
  PORT: 8001
  ITEMSBOXING_JWT_KEY: "CF64C4AE-AE2E-4277-B20F-917B6740A22E"
  FLASK_DEBUG: false
  FLASK_ENV: "Production"

initContainers: []

startupCommand:
  enabled: true
  command: ["ddtrace-run"]
  args: ["uwsgi", "--ini" ,"wsgi.ini", "--enable-threads"]

secret:
  enabled: true

image:
  repository: __IMAGE-REPOSITORY__
  pullPolicy: Always
  tag: latest

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8001

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
  hosts:
    - host: ""
      http:
        paths:
          - path: /api/items-boxing
            pathType: Prefix
            backend:
              service:
                name: wms-items-boxing-helm-service
                port:
                  number: 80

resources:
  limits:
    cpu: 300m
    memory: 600Mi
  requests:
    cpu: 150m
    memory: 350Mi

autoscaling:
  enabled: true
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 75
  minReplicas: 2
  maxReplicas: 6

readinessProbe:
  httpGet:
    path: /api/items-boxing/health/
    port: 8001
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
  failureThreshold: 5

nodeSelector:
 agentpool: ""

tolerations:
  - key: "kubernetes.azure.com/scalesetpriority"
    operator: "Equal"
    value: "spot"
    effect: "NoSchedule"

affinity: {}
